// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zqdudwiswywhtfiyfiyy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpxZHVkd2lzd3l3aHRmaXlmaXl5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4MTAwNzEsImV4cCI6MjA2MjM4NjA3MX0.PzM5IHgbvE70w-8lZBknmrwbx1vlg0aDGL1-E2rB0ww";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);